FROM python:3.12

WORKDIR /app

COPY ../dataset dataset/

COPY ../requirements.txt .
RUN pip install -r requirements.txt

COPY ../.env .env
COPY ../src src/

RUN python -m src.rag.database_init

ENTRYPOINT ["python", "-m", "src.server"]